/**
 * Common types shared across the application.
 *
 * This file contains base types that don't belong to a specific feature.
 * In a larger app, you might have more shared types here.
 */

/**
 * Generic ID type for entities.
 * Using string for UUIDs generated by crypto.randomUUID().
 *
 * Learning Note:
 * Type aliases like this make code more semantic and easier to refactor.
 * If we later decide to use numbers instead of strings, we change it once here.
 */
export type EntityId = string;

/**
 * Timestamp in milliseconds since Unix epoch.
 * Generated using Date.now().
 *
 * Example: 1704067200000 represents 2024-01-01 00:00:00 UTC
 */
export type Timestamp = number;
